src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usager", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $usager;

    /**
     * @ORM\Column(type="date")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="boolean")
     */
    private $statut;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneCommande", mappedBy="commande")
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsager(): ?Usager
    {
        return $this->usager;
    }

    public function setUsager(?Usager $usager): self
    {
        $this->usager = $usager;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes->removeElement($ligneCommande);
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/commande", name="commande_")
 */
class CommandeController extends AbstractController
{

    /**
     * Undocumented function
     * 
     * @Route("/", name="index")
     */
    public function index()
    {
        return $this->render('commande/index.html.twig', [
            'current_menu' => 'commande',
            'commandes' => $this->getUser()->getCommandes(),
        ]);
    }

    /**
     * Undocumented function
     * 
     * @Route("/show/{idCommande}", name="show")
     *
     * @param Commande $commande
     * @return void
     */
    public function show(Commande $idCommande)
    {
        return $this->render('commande/show.html.twig', [
            'current_menu' => 'commande',
            'commande' => $idCommande
        ]);
    }
}

templates/commande/index.html.twig
{% extends "base.html.twig" %}
{% block title %}Vos commandes{% endblock title %}

{% block header %}
    <h1 class="text-center">Vos commandes</h1>
{% endblock header %}

{% block body %}
{% for flashMessage in app.flashes('success') %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{flashMessage}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<table class="table table-hover">
    <thead>
        <tr>
            <th>N°</th>
            <th>Date</th>
            <th class="text-center">Statut</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for commande in commandes %}
            <tr class="{% if commande.statut %}text-success{% else %}text-danger{% endif %}">
                <td>{{commande.id}}</td>
                <td>{{commande.dateCommande|date('d/m/Y')}}</td>
                <td class="text-center">
                    {% if commande.statut %}
                    <i class="fas fa-check-square fa-2x"></i>
                    {% else %}
                    <i class="fas fa-hourglass-half fa-2x"></i>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('commande_show', {'idCommande': commande.id})}}" class="btn btn-primary">Voir</a>
                </td>
            </tr>
        {% else %}
        <tr>
            <td colspan="6" class="alert alert-warning">Vous n'avez pas passé de commande pour le moment...</td>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock body %}

templates/commande/show.html.twig
{% extends "base.html.twig" %}
{% block title %}Vos commandes{% endblock title %}

{% block header %}
    <h1 class="text-center">Vos commandes</h1>
{% endblock header %}

{% block body %}
<table class="table table-hover">
    <thead>
        <tr>
            <th>Produit</th>
            <th>Quantité</th>
            <th>Prix unitaire</th>
        </tr>
    </thead>
    <tbody>
        {% for ligne in commande.ligneCommandes %}
            <tr>
                <td>{{ligne.article.libelle}}</td>
                <td>{{ligne.quantite}}</td>
                <td>{{ligne.prix}}</td>
            </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock body %}